### ISSUE TITLE
TabList Name Problem

### ISSUE THREAD

**Issue by InceDev** [InventivetalentDev/Murder#3]
## What steps will reproduce the problem?  
1. At the end of the match

## What were you expecting to happen? What happened instead?  
When finishes a match killing the murder, his name disappear in the tab.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.1.2

## What Spigot version are you using? *Type /version*  
spigot 1.9.2

## What plugins ae you using? *Type /plugins*  
[23:06:37 INFO]: Plugins (9): PermissionsEx, ResourcePackApi, WorldEdit, ViaVersion, MenuBuilder, PacketListenerApi, NickNamer, NPCLib, Murder

**Comment by InventivetalentDev** [comment]
Does this only happen for the the player who is assigned as Murderer or for other players as well?
Please test it in multiple rounds and see if it's caused by something different (for example that it's always you disappearing, or another specific player).  

Please also try running /refreshNick <player name> for the player who disappeared and see if that changes anything.

**Comment by HiperBulu** [comment]
Solved This problem with a script
